export const siteProfile = {
  brand: 'WATAN',
  handle: '@w.awakalaey',
  email: 'w.awakalaey@gmail.com',
  locationKu: 'کوردستان، عێراق',
  locationEn: 'Kurdistan, Iraq',
  github: '#',
  linkedin: '#',
};

export const translations = {
  ku: {
    langName: 'کوردی', switchTo: 'English', dir: 'rtl',
    nav: ['سەرەتا', 'دەربارە', 'تواناکان', 'پڕۆژەکان', 'پەیوەندی'],
    heroBadge: 'بەخێربێیت بۆ پۆرتفۆلیۆکەم',
    hello: 'سڵاو، من',
    name: 'حەمە وەتەن',
    rolePrefix: 'شارەزام لە',
    roles: ['گەشەپێدانی وێب', 'دروستکردنی سیستەم', 'سایبەر سیکیوریتی', 'چارەسەری دیجیتاڵ'],
    heroText: 'وێبسایت و سیستەمی مۆدێرن، خێرا و ڕیسپۆنسیڤ دروست دەکەم؛ بە دیزاینێکی پاک، ئەزموونی بەکارهێنەری جوان و کۆدی ڕێکخراو.',
    viewProjects: 'بینینی پڕۆژەکان', contactMe: 'پەیوەندیم پێوە بکە', available: 'ئامادەم بۆ پڕۆژەی نوێ',
    aboutEyebrow: 'دەربارەی من',
    aboutTitle: 'بیرۆکەکان دەگۆڕم بۆ ئەزموونی دیجیتاڵی کاریگەر',
    about1: 'من وەتەنم، حەزم لە دروستکردنی وێبسایت و سیستەمی جوان و بەسوودە. سەرنجم لەسەر وردەکاری، خێرایی و ئاسانی بەکارهێنانە.',
    about2: 'لە هەر پڕۆژەیەکدا هەوڵ دەدەم دیزاین، تەکنەلۆژیا و پێداویستییە ڕاستەقینەکانی بەکارهێنەر یەکبخەم.',
    stats: [['+2', 'فێربوون و ئەزموون'], ['+15', 'پڕۆژە و تاقیکردنەوە'], ['2', 'زمانی پۆرتفۆلیۆ']],
    qualities: ['کۆدی پاک', 'ڕیسپۆنسیڤ', 'پارێزراو', 'خێرا'],
    skillsEyebrow: 'تواناکان', skillsTitle: 'تەکنەلۆژیا و ئامرازەکان', skillsText: 'کۆمەڵێک تەکنەلۆژیا بۆ دروستکردنی وێبسایت و سیستەمی تەواو.',
    services: [
      ['bi-window-stack', 'Front-end', 'دیزاینی مۆدێرن، ڕیسپۆنسیڤ و جوڵەی نەرم بۆ هەموو ئامێرەکان.'],
      ['bi-database-check', 'Back-end', 'API، داتابەیس، لۆجیکی سیستەم و بەڕێوەبردنی داتا.'],
      ['bi-shield-lock', 'Security First', 'پاراستنی داتا، RLS و ڕێکخستنی دەسەڵات بە شێوەی پارێزراو.'],
    ],
    projectsEyebrow: 'هەڵبژاردەی کارەکان', projectsTitle: 'پڕۆژە دیارەکان', noProjects: 'هێشتا پڕۆژەیەک زیاد نەکراوە.', openProject: 'کردنەوەی پڕۆژە', sourceCode: 'کۆدی سەرچاوە',
    contactEyebrow: 'پەیوەندی', contactTitle: 'بیرۆکەیەکت هەیە؟ با پێکەوە دروستی بکەین.', contactText: 'نامەیەک بنێرە؛ زووترین کات وەڵامت دەدەمەوە.',
    form: { name: 'ناوی تەواو', email: 'ئیمەیڵ', subject: 'بابەت', message: 'نامە', send: 'ناردنی نامە', sending: 'دەنێردرێت...', success: 'سوپاس! نامەکەت بە سەرکەوتوویی نێردرا.', error: 'هەڵەیەک ڕوویدا. تکایە دووبارە هەوڵ بدەرەوە.' },
    footer: 'بە حەز و وردەکاری دروستکراوە.', rights: 'هەموو مافەکان پارێزراون.', location: 'شوێن', emailLabel: 'ئیمەیڵ',
  },
  en: {
    langName: 'English', switchTo: 'کوردی', dir: 'ltr',
    nav: ['Home', 'About', 'Skills', 'Projects', 'Contact'],
    heroBadge: 'Welcome to my portfolio', hello: 'Hello, I am', name: 'Watan Hama', rolePrefix: 'I work in',
    roles: ['Web Development', 'System Building', 'Cybersecurity', 'Digital Solutions'],
    heroText: 'I build modern, fast and responsive websites and systems with clean design, polished user experience and well-structured code.',
    viewProjects: 'View projects', contactMe: 'Contact me', available: 'Available for new projects',
    aboutEyebrow: 'About me', aboutTitle: 'Turning ideas into impactful digital experiences',
    about1: 'I am Watan, passionate about building useful and beautiful websites and systems. I focus on detail, speed and ease of use.',
    about2: 'In every project, I combine design, technology and real user needs to create a result that feels complete.',
    stats: [['2+', 'Learning & experience'], ['15+', 'Projects & experiments'], ['2', 'Portfolio languages']],
    qualities: ['Clean code', 'Responsive', 'Secure', 'Fast'],
    skillsEyebrow: 'Capabilities', skillsTitle: 'Technologies & tools', skillsText: 'A practical toolkit for building complete websites and systems.',
    services: [
      ['bi-window-stack', 'Front-end', 'Modern responsive interfaces and smooth motion for every device.'],
      ['bi-database-check', 'Back-end', 'APIs, databases, system logic and dependable data workflows.'],
      ['bi-shield-lock', 'Security First', 'Data protection, Row Level Security and carefully controlled access.'],
    ],
    projectsEyebrow: 'Selected work', projectsTitle: 'Featured projects', noProjects: 'No projects have been added yet.', openProject: 'Open project', sourceCode: 'Source code',
    contactEyebrow: 'Contact', contactTitle: 'Have an idea? Let us build it together.', contactText: 'Send a message and I will get back to you as soon as possible.',
    form: { name: 'Full name', email: 'Email', subject: 'Subject', message: 'Message', send: 'Send message', sending: 'Sending...', success: 'Thank you! Your message was sent successfully.', error: 'Something went wrong. Please try again.' },
    footer: 'Crafted with passion and attention to detail.', rights: 'All rights reserved.', location: 'Location', emailLabel: 'Email',
  },
};

export const sampleProjects = [
  {
    id: 'sample-1',
    title_ku: 'سیستەمی بەڕێوەبردنی سەرمایە',
    title_en: 'Capital Management System',
    description_ku: 'داشبۆردێکی ڕیسپۆنسیڤ بۆ مامەڵە، قازانج، قەرز و ڕاپۆرت.',
    description_en: 'A responsive dashboard for transactions, profit, debt and reporting.',
    tech: ['Next.js', 'Supabase', 'Bootstrap'],
    image_url: null,
    project_url: '#',
    github_url: '#',
    sort_order: 1,
    is_published: true,
  },
  {
    id: 'sample-2',
    title_ku: 'چات ئەپلیکەیشن',
    title_en: 'Chat Application',
    description_ku: 'ڕووکارێکی خێرا و سادە بۆ نامە و پەیوەندییە ڕاستەوخۆکان.',
    description_en: 'A fast and simple interface for direct messages and communication.',
    tech: ['React', 'Node.js', 'Socket.io'],
    image_url: null,
    project_url: '#',
    github_url: '#',
    sort_order: 2,
    is_published: true,
  },
];
